### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by ismailkoksal** [EdjeElectronics/OpenCV-Playing-Card-Detector#7]
```python
Traceback (most recent call last):
    File "CardDetector.py", line 66, in <module>
        cnts_sort, cnt_is_card = Cards.find_cards(pre_proc)
    File "/home/ismail/Documents/OpenCV-Playing-Card-Detector/Cards.py", line 135, in find_cards
        dummy,cnts,hier = cv2.findContours(thresh_image,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
```

**Comment by ismailkoksal** [comment]
Updating OpenCV fixed issue.
